services:
  cloudburst:
    build:
      context: .
      network: host
    shm_size: "1gb"
    image: cloudburst
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      - AWS_REGION=us-west-2
      - BUCKET_NAME=docker-pystrata-test
      - MODE_STR=
      - LOCAL_MODE=0
      - WORK_ITEM=middle/m5p0*
    volumes:
      # Enable if LOCAL_MODE=1 to use local files
      # - ./data/input:/work/input:ro
      - ./data/output:/work/output:rw
      - ~/.aws/credentials:/root/.aws/credentials:ro
