services:
  cloudburst1:
    build:
      context: .
      network: host
    shm_size: "1gb"
    image: cloudburst1
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      - AWS_REGION=us-west-2
      - BUCKET_NAME=docker-pystrata-test
      - MODE_STR=
      - LOCAL_MODE=1
      - MOTION=m5p0-*
      - PROFILE=middle.pkl
    volumes:
      - ./data/motions:/work/motions:ro
      - ./data/profiles:/work/profiles:ro
      - ./data/output:/work/output:rw
      - ~/.aws/credentials:/root/.aws/credentials:ro
